name: pr-tests
on: [push]
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Vercel
        uses: mskelton/wait-for-vercel-action@v1.2.0
        id: wait-for-vercel
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress.io
        uses: cypress-io/github-action@v2.7.0
        env:
          CYPRESS_BASE_URL: ${{ steps.wait-for-vercel.outputs.url }}
  wait-for-vercel-deployment:
    runs-on: ubuntu-18.04
    steps:
      - name:
          Retrieve deployment URL (example on how to set an ENV var)
        run:
          'echo VERCEL_DEPLOYMENT_URL=scottspence-com.now.sh >>
          $GITHUB_ENV'

      - uses: UnlyEd/github-action-await-vercel@v1.1.0
        id: await-vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          deployment-url: ${{ env.VERCEL_DEPLOYMENT_URL }}
          timeout: 10 # Wait for 10 seconds before failing

      - name:
          Displays the deployment name (example on how to read
          information about the deployment)
        run:
          'echo My deployment is ${{
          fromJson(steps.await-vercel.outputs.deploymentDetails).name
          }}'
