name: pr-tests
on: [push]
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Vercel
        uses: UnlyEd/github-action-await-vercel@v1.1.0
        id: await-vercel
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress.io
        uses: cypress-io/github-action@v2.7.0
        env:
          CYPRESS_BASE_URL: fromJson(steps.await-vercel.outputs.deploymentDetails).url
